# Generated by Django 3.1.4 on 2021-09-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['horario']},
        ),
    ]
